namespace: kube-system

commonLabels:
  app: helm
  name: tiller
  version: v2.15.1

images:
  - name: gcr.io/kubernetes-helm/tiller
    newTag: v2.15.1

resources:
  - service-account.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
