---
# Source: sealed-secrets/templates/service-account.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0


---
# Source: sealed-secrets/templates/cluster-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-unsealer
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0
rules:
  - apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete


---
# Source: sealed-secrets/templates/cluster-role-binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-unsealer
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: sealed-secrets-controller
    namespace: kube-system


---
# Source: sealed-secrets/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secrets-key-admin
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0
rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-key
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create


---
# Source: sealed-secrets/templates/role-binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-key-admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: sealed-secrets-controller
    namespace: kube-system


---
# Source: sealed-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: sealed-secrets

---
# Source: sealed-secrets/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-1.0.2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/version: 0.7.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets
      app.kubernetes.io/instance: sealed-secrets-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sealed-secrets
        app.kubernetes.io/instance: sealed-secrets-controller
    spec:
      serviceAccountName: sealed-secrets-controller
      containers:
        - name: sealed-secrets-controller
          command:
            - controller
          args:
            - "--key-name"
            - "sealed-secrets-key"
          image: quay.io/bitnami/sealed-secrets-controller:v0.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          resources:
            {}
            

---
# Source: sealed-secrets/templates/sealedsecret-crd.yaml


