apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: podinfo
spec:
  secretName: podinfo-tls
  issuerRef:
    name: podinfo
    kind: Issuer
  commonName: podinfo.test
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - podinfo.test
