
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: podinfo
spec:
  ingressClassName: nginx
  rules:
  - host: podinfo.test
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 9898
        pathType: Prefix
        path: /
  tls:
  - hosts:
    - podinfo.test
    secretName: podinfo-tls
