namespace: default

commonLabels:
  app: podinfo
  version: "4.0.6"

images:
  - name: stefanprodan/podinfo
    newTag: "4.0.6"

resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  - issuer.yaml
  - certificate.yaml
  - ingress.yaml
