namespace: kube-system

commonLabels:
  app: local-path-storage

resources:
  - service-account.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - configmap.yaml
  - deployment.yaml
  - storage-class.yaml
